apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: footprint-spike-appset
  namespace: argocd
spec:
  goTemplate: true # <--- ADD THIS LINE
  generators:
    - clusters: {} 
  template:
    metadata:
      # We'll use "name" here just in case the label is missing on the local cluster
      name: 'spike-nginx-{{ .name }}' 
    spec:
      project: default
      source:
        repoURL: https://github.com/footprint-it-solutions/argocd-managed-spike
        targetRevision: HEAD
        path: argocd/applications/spike-test
        helm:
          releaseName: spike-nginx
     destination:
  name: in-cluster  # Use the name 'in-cluster' instead of the server URL
  namespace: spike-test-ns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true