apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spike-test-app
  namespace: argocd
spec:
  generators:
    - clusters: {} 
  goTemplate: true
  template:
    metadata:
      # Changed from 'cluster-name' label to the built-in '.name' 
      # This will result in: spike-test-in-cluster
      name: 'spike-test-{{ .name }}'
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        # Update this to 18.2.1 or simply use 18.x
        targetRevision: 18.2.1 
        helm:
          releaseName: spike-test
      destination:
        namespace: spike-test-ns
        server: '{{ .server }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true