apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spike-test-app
  namespace: argocd
spec:
  generators:
    - clusters: {} 
  goTemplate: true
  template:
    metadata:
      # Using .name as a fallback if the cluster-name label is missing
      name: 'spike-test-{{ index .metadata.labels "cluster-name" | default .name }}'
    spec:
      project: default
      sources:
        # Source 1: The official Helm Chart
        - repoURL: https://charts.bitnami.com/bitnami
          chart: nginx
          targetRevision: 15.1.1
          helm:
            # This tells Argo CD to look for a values file in "Source 2"
            valueFiles:
              - '$values/argocd/applications/spike-test/values.yaml'
        
        # Source 2: Your Git Repo (assigned the reference "values")
        - repoURL: https://github.com/footprint-it-solutions/argocd-managed-spike.git
          targetRevision: HEAD
          ref: values
      
      destination:
        namespace: spike-test-ns
        server: '{{ .server }}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true