apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spike-nginx
  template:
    metadata:
      labels:
        app: spike-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
